# Generated by Django 5.2.8 on 2025-12-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('physical', models.IntegerField()),
                ('mental', models.IntegerField()),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
